### ISSUE TITLE
a new sign textur 

### ISSUE THREAD

**Issue by Lukas64-the-dog** [Tim3Game/The-Expanded-Signs-Pack#1]
for the pack this pack needs german freeway signs 
![motorway_blue_lt_arrow_sign_blue](https://user-images.githubusercontent.com/70535025/91746875-9d61cc80-ebbd-11ea-8e7c-7bb3d34c82fe.png)

**Comment by Tim3Game** [comment]
I'm currently reworking how the highway signs (actually all the bigger signs) work, so it will probably take some time until I get all the things ready, but I could add German specific stuff too. But the pack will be probably available when Immersive Vehicles V19 will be releases (because of the way how signs are done, mainly texts on them), that means that the pack and this German type signs will work only on Immersive Vehicles version 19 and higher.
