### ISSUE TITLE
cannot make a modular motorway sign in game.

### ISSUE THREAD

**Issue by HJL41** [Tim3Game/The-Expanded-Signs-Pack#3]
Hi i was looking for a mod that could add realistic highway signs and i found your mod because it had a picture of it in the curse forge page. And that was what i was looking for. But when i entered the game and tried to make one, it didnt work and i have no idea how to make thoese signs please help me. But im not sure the mod is continued as it last update was in 2019, and the last github issue was posted in 2020. Please tell me if this mods is continued or discontinued.

**Comment by Tim3Game** [comment]
Hello.
Yeah sorry, I should update the CurseForge page because I don't work on TESP anymore. I know that it worked for a long time but I guess they again changed something and it broke it. But even if, it didn't had much options anyway, so sorry to ruin your hopes.
But it's a long time, there surly must be some other signs pack that adds highway signs too. And if not, I suggest you to look for a alternative mod, because then you can maybe get lucky and find one that allows you better editing of the signs then just few text fields.
